global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'optiRoute_ai'
    static_configs:
      - targets: ['localhost:8000']
        labels:
          service: 'optiRoute'
          environment: 'development'
